# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# 网站设置
title: WEB前端开发
author: 硕鼠宝
qq: 759979885
email: 759979885@qq.com
description: 专注前端开发，关注用户体验
keywords: 硕鼠宝 FE 前端 JS
baseurl:
url: http://shuoshubao.github.io
pathname: shuoshubao.github.io

# 编译设置
markdown: kramdown

# 设置 sass 路径 + 压缩
sass:
    sass_dir: sta/_sass
    style: :compressed

# 不编译的目录/文件
exclude: ['node_modules', 'gulpfile.js', 'package.json', 'CNAME']

# 用将来的日期发布文章
future: true
